"""
Event definitions for the trading engine.

This module defines all events used in the event-driven architecture.
Events are immutable dataclasses that flow through the event bus.
"""

from dataclasses import dataclass, field
from datetime import datetime
from typing import Optional, Dict, Any
from enum import Enum


class EventType(str, Enum):
    """Event type enumeration."""
    # Market Data Events
    TRADE_TICK_RECEIVED = "trade_tick_received"
    CANDLE_COMPLETED = "candle_completed"
    MARKET_DATA_CONNECTION_LOST = "market_data_connection_lost"
    MARKET_DATA_CONNECTION_RESTORED = "market_data_connection_restored"

    # Analytics Events
    ANALYTICS_UPDATED = "analytics_updated"
    ORDER_FLOW_IMBALANCE_DETECTED = "order_flow_imbalance_detected"
    MICROSTRUCTURE_PATTERN_DETECTED = "microstructure_pattern_detected"
    DATA_QUALITY_ISSUE = "data_quality_issue"

    # Trading Events
    TRADING_SIGNAL_GENERATED = "trading_signal_generated"
    TRADING_SIGNAL_REJECTED = "trading_signal_rejected"
    ORDER_PLACED = "order_placed"
    ORDER_FILLED = "order_filled"
    ORDER_FAILED = "order_failed"
    ORDER_CANCELLED = "order_cancelled"

    # Position Events
    POSITION_OPENED = "position_opened"
    POSITION_UPDATED = "position_updated"
    POSITION_CLOSED = "position_closed"
    TRAILING_STOP_HIT = "trailing_stop_hit"

    # Portfolio Risk Events
    DUMP_DETECTED = "dump_detected"
    PORTFOLIO_HEALTH_DEGRADED = "portfolio_health_degraded"
    CORRELATED_DUMP_DETECTED = "correlated_dump_detected"
    CIRCUIT_BREAKER_TRIGGERED = "circuit_breaker_triggered"
    MAX_HOLD_TIME_EXCEEDED = "max_hold_time_exceeded"
    FORCE_EXIT_REQUIRED = "force_exit_required"

    # System Events
    SYSTEM_ERROR = "system_error"
    SYSTEM_STARTED = "system_started"
    SYSTEM_SHUTDOWN = "system_shutdown"
    COMPONENT_HEALTH_CHECK = "component_health_check"

    # Mempool Events (EVM only)
    OUR_TRANSACTION_PENDING = "our_transaction_pending"
    OUR_TRANSACTION_CONFIRMED = "our_transaction_confirmed"
    OUR_TRANSACTION_FAILED = "our_transaction_failed"
    LARGE_PENDING_SWAP = "large_pending_swap"
    MEV_BOT_DETECTED = "mev_bot_detected"

    # Notification Events
    NOTIFICATION_SENT = "notification_sent"
    NOTIFICATION_FAILED = "notification_failed"


class OrderSide(str, Enum):
    """Order side enumeration."""
    BUY = "buy"
    SELL = "sell"


class OrderType(str, Enum):
    """Order type enumeration."""
    MARKET = "market"
    LIMIT = "limit"
    STOP_LOSS = "stop_loss"
    STOP_LIMIT = "stop_limit"


class OrderStatus(str, Enum):
    """Order status enumeration."""
    PENDING = "pending"
    PLACED = "placed"
    PARTIALLY_FILLED = "partially_filled"
    FILLED = "filled"
    CANCELLED = "cancelled"
    FAILED = "failed"
    REJECTED = "rejected"


@dataclass(frozen=True)
class Event:
    """Base event class."""
    event_type: EventType = field(init=False)
    timestamp: datetime = field(default_factory=datetime.utcnow, init=False)
    metadata: Dict[str, Any] = field(default_factory=dict, init=False)


# ============================================================================
# TRADING EVENTS
# ============================================================================

@dataclass(frozen=True)
class TradingSignalGenerated(Event):
    """Trading signal generated by decision engine."""
    event_type: EventType = field(default=EventType.TRADING_SIGNAL_GENERATED, init=False)

    symbol: str
    side: OrderSide
    signal_strength: float
    confluence_score: float

    # Entry parameters
    entry_price: Optional[float] = None

    # Risk management
    stop_loss: Optional[float] = None
    take_profit: Optional[float] = None
    position_size_pct: float = 2.0

    # Signal metadata
    primary_signals: Dict[str, Any] = field(default_factory=dict)
    filter_scores: Dict[str, float] = field(default_factory=dict)

    # Market context
    exchange: str = "binance"
    market_type: str = "spot"
    timeframe: str = "1m"


@dataclass(frozen=True)
class OrderPlaced(Event):
    """Order successfully placed on exchange."""
    event_type: EventType = field(default=EventType.ORDER_PLACED, init=False)

    order_id: str
    symbol: str
    side: OrderSide
    order_type: OrderType
    quantity: float
    exchange: str

    exchange_order_id: Optional[str] = None
    price: Optional[float] = None
    status: OrderStatus = OrderStatus.PLACED

    # Link to original signal
    signal_id: Optional[str] = None


@dataclass(frozen=True)
class OrderFilled(Event):
    """Order successfully filled."""
    event_type: EventType = field(default=EventType.ORDER_FILLED, init=False)

    order_id: str
    exchange_order_id: str
    symbol: str
    side: OrderSide
    quantity: float
    filled_quantity: float
    avg_fill_price: float
    exchange: str

    status: OrderStatus = OrderStatus.FILLED

    # Execution details
    commission: float = 0.0
    commission_asset: str = "USDT"

    # Link to original signal
    signal_id: Optional[str] = None


@dataclass(frozen=True)
class OrderFailed(Event):
    """Order failed to execute."""
    event_type: EventType = field(default=EventType.ORDER_FAILED, init=False)

    order_id: str
    symbol: str
    side: OrderSide
    error_message: str
    exchange: str

    error_code: Optional[str] = None
    retry_count: int = 0
    is_retriable: bool = False

    # Link to original signal
    signal_id: Optional[str] = None


@dataclass(frozen=True)
class OrderCancelled(Event):
    """Order cancelled."""
    event_type: EventType = field(default=EventType.ORDER_CANCELLED, init=False)

    order_id: str
    symbol: str
    reason: str
    exchange: str

    exchange_order_id: Optional[str] = None


# ============================================================================
# POSITION EVENTS
# ============================================================================

@dataclass(frozen=True)
class PositionOpened(Event):
    """Position successfully opened."""
    event_type: EventType = field(default=EventType.POSITION_OPENED, init=False)

    position_id: str
    symbol: str
    side: OrderSide
    entry_price: float
    quantity: float
    exchange: str
    market_type: str

    # Risk parameters
    stop_loss: Optional[float] = None
    take_profit: Optional[float] = None
    trailing_stop_distance_pct: float = 0.5

    # Link to original signal and order
    signal_id: Optional[str] = None
    order_id: Optional[str] = None


@dataclass(frozen=True)
class PositionClosed(Event):
    """Position closed."""
    event_type: EventType = field(default=EventType.POSITION_CLOSED, init=False)

    position_id: str
    symbol: str
    side: OrderSide
    entry_price: float
    exit_price: float
    quantity: float
    exchange: str
    exit_reason: str  # "stop_loss", "take_profit", "trailing_stop", "manual", "risk_manager"

    # P&L
    realized_pnl: float = 0.0
    realized_pnl_pct: float = 0.0

    # Duration
    hold_duration_seconds: float = 0.0


# ============================================================================
# SYSTEM EVENTS
# ============================================================================

@dataclass(frozen=True)
class SystemError(Event):
    """Critical system error."""
    event_type: EventType = field(default=EventType.SYSTEM_ERROR, init=False)

    component: str
    error_type: str
    error_message: str

    traceback: Optional[str] = None
    is_critical: bool = True

